### ISSUE TITLE
CircleCIを導入してみよう

### ISSUE THREAD

**Issue by travelist** [ShotaTogawa/caffeine#1]
Circle CI といって、githubにコードをプッシュすると自動で指定した処理をしてくれるサービスがあるので導入しよう。

ruby には **rubocop** といってコードの**規約チェック**をしてくれる(同じ処理をする場合でもプログラムの書き方は何通りかあるので、コードを見やすくするためにルール/規約を決めたりする。それをrubocop は正しくルールに従っているのかをチェックしてくれる。)Gem があるので、それを導入した上で、circleCI上で毎回 rubocop の規約チェックが実行されるようにしてみよう。

ローカル環境にて。

- Gemfile に rubocop を追加
- bundle install してrubocop をインストールし、rubocop をローカルで実行してみる
- rubocop は自動で設定ファイルを書いてくれるので、(コマンドの使い方を調べる) .robucop_todo.yml を作成
- circleCI のサービスのアカウントを作成, このレポジトリをwatchするようにする
- circle.yml ファイルを作成し、test のフェイズで rubocop コマンドを実行するように指定
- 実際にコードを push してみて、circleCI のログをみたときに rubocop が実行されていれば完了
- そしたらこのissueをクローズしてください。

**Comment by travelist** [comment]
@ShotaTogawa 

circle.yml というファイルが必要。
たぶん以下の用な内容になるはず。
こうすることで、コードをプッシュするたびに rubocop が走る。

```
machine:
  timezone:
    Asia/Tokyo
  ruby:
    version: 2.2.3
  environment:
    RAILS_ENV: test

test:
  pre:
    - bundle exec rubocop
```
